### ISSUE TITLE
Please create GitHub releases for version control

### ISSUE THREAD

**Issue by favoyang** [PixelWizards/com.pixelwizards.utilities#2]
Hi @gekidoslair,

Please create an GitHub releases, so the OpenUPM can process the repository. The git tag name shall equal with the version in the package.json `0.1.0-preview.2`

**Comment by gekidoslair** [comment]
Ah! Great will do!

**Comment by gekidoslair** [comment]
this is done - did a package bump to preview.3 along with the tag!

**Comment by favoyang** [comment]
Yes, please checkout the version history section: https://openupm.com/packages/com.pixelwizards.utilities/
