### ISSUE TITLE
Multiscene loader has using statements to UnityEditor

### ISSUE THREAD

**Issue by aschearer** [PixelWizards/com.pixelwizards.utilities#3]
These prevent the player from building. One fix would be to wrap them in an ifdef.

**Comment by gekidoslair** [comment]
doh! good find - I'll get this fixed and push a new version!

**Comment by gekidoslair** [comment]
fixed in in commit:
https://github.com/PixelWizards/com.pixelwizards.utilities/commit/2bbc8783f6ef5cf87dcce3ace2a7145176b230c7
