### ISSUE TITLE
Multiscene loader doesn't load scenes at runtime

### ISSUE THREAD

**Issue by aschearer** [PixelWizards/com.pixelwizards.utilities#4]
Seems to repro with the runtime sample in the project. At runtime in the player I get the following errors:

> Scene config doesn't have any scenes defined - nothing to load!

I have included the runtime and config scene in the build settings.
Some debugging indicates that the Object in the scene config is null. It's not null in editor.

**Comment by gekidoslair** [comment]
Hey sorry for the lag - just spotted this. 

So you've added the scenes that you are trying to load in the config into your project's build settings (ie under file->build settings)? 

That should be all that's needed - I'll see if I can reproduce this. Thanks for reporting!

**Comment by gekidoslair** [comment]
hmm...just tested it out with the samples in the project and also on my personal project and the runtime loading is working from my side? Can you provide more details or maybe a repro project so I can see what might be causing the problem?

**Comment by gekidoslair** [comment]
have done a bunch of work on the multiscene loader & runtime support, hopefully should resolve this issue.
